Resources:
  CodespacesRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - rolesanywhere.amazonaws.com
            Action: 
              - sts:AssumeRole
              - sts:SetSourceIdentity
              - sts:TagSession
      Path: /
      Policies:
        - PolicyName: s3-access
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action: s3:*
                Resource: "*"
      Tags:
        - Key: openrolesanywhere
          Value: true

Outputs:
  RoleArn:
    Value: !GetAtt CodespacesRole.Arn
